In [ ]:
import geopandas

gdf = geopandas.read_file("Lower_layer_Super_Output_Areas_December_2021_Boundaries_EW_BSC_V4_6453788336260919790.gpkg")

In [ ]:
filtered_gdf = gdf[gdf["LSOA21NM"].str.contains(
    "Devon|Torbay|South Hams|Exeter|Torridge|Teignbridge|Plymouth"
    )]

In [ ]:
filtered_gdf.to_file("LSOA_Devon_2021_EW_BSC_V4.gpkg")

Confirm the written file is valid.

In [ ]:
filtered_gdf_read = geopandas.read_file("LSOA_Devon_2021_EW_BSC_V4.gpkg")
filtered_gdf_read.plot()

## IMD Data

In [2]:
import pandas as pd

In [ ]:

imd_df = pd.read_excel("File_1_IoD2025_Index_of_Multiple_Deprivation.xlsx", sheet_name="IMD25")

In [ ]:
imd_df.head()

In [ ]:
filtered_imd_df = imd_df[imd_df["LSOA name (2021)"].str.contains(
    "Devon|Torbay|South Hams|Exeter|Torridge|Teignbridge|Plymouth"
    )]

In [ ]:
filtered_imd_df.to_csv("devon_imd_2025_2021_LSOAs.csv", index=False)

## Demand

In [5]:
population_df = pd.read_excel("sapelsoasyoa20222024.xlsx", sheet_name="Mid-2024 LSOA 2021", skiprows=3)

In [6]:
population_df.head()

,LAD 2023 Code,LAD 2023 Name,LSOA 2021 Code,LSOA 2021 Name,Total,F0,F1,F2,F3,F4,...,M81,M82,M83,M84,M85,M86,M87,M88,M89,M90
0,E06000001,Hartlepool,E01011949,Hartlepool 009A,1898,6,7,16,3,11,...,3,3,4,5,1,1,2,2,2,3
1,E06000001,Hartlepool,E01011950,Hartlepool 008A,1247,11,10,7,14,13,...,0,2,1,0,0,1,0,0,0,0
2,E06000001,Hartlepool,E01011951,Hartlepool 007A,1393,5,11,9,9,12,...,1,0,0,1,3,2,0,1,0,1
3,E06000001,Hartlepool,E01011952,Hartlepool 002A,1669,10,12,12,10,17,...,0,3,2,1,3,3,3,2,4,5
4,E06000001,Hartlepool,E01011953,Hartlepool 002B,2303,15,15,7,20,22,...,3,3,4,3,3,1,0,1,0,2

In [34]:
[i for i in population_df.columns]

['LAD 2023 Code',
 'LAD 2023 Name',
 'LSOA 2021 Code',
 'LSOA 2021 Name',
 'Total',
 'F0',
 'F1',
 'F2',
 'F3',
 'F4',
 'F5',
 'F6',
 'F7',
 'F8',
 'F9',
 'F10',
 'F11',
 'F12',
 'F13',
 'F14',
 'F15',
 'F16',
 'F17',
 'F18',
 'F19',
 'F20',
 'F21',
 'F22',
 'F23',
 'F24',
 'F25',
 'F26',
 'F27',
 'F28',
 'F29',
 'F30',
 'F31',
 'F32',
 'F33',
 'F34',
 'F35',
 'F36',
 'F37',
 'F38',
 'F39',
 'F40',
 'F41',
 'F42',
 'F43',
 'F44',
 'F45',
 'F46',
 'F47',
 'F48',
 'F49',
 'F50',
 'F51',
 'F52',
 'F53',
 'F54',
 'F55',
 'F56',
 'F57',
 'F58',
 'F59',
 'F60',
 'F61',
 'F62',
 'F63',
 'F64',
 'F65',
 'F66',
 'F67',
 'F68',
 'F69',
 'F70',
 'F71',
 'F72',
 'F73',
 'F74',
 'F75',
 'F76',
 'F77',
 'F78',
 'F79',
 'F80',
 'F81',
 'F82',
 'F83',
 'F84',
 'F85',
 'F86',
 'F87',
 'F88',
 'F89',
 'F90',
 'M0',
 'M1',
 'M2',
 'M3',
 'M4',
 'M5',
 'M6',
 'M7',
 'M8',
 'M9',
 'M10',
 'M11',
 'M12',
 'M13',
 'M14',
 'M15',
 'M16',
 'M17',
 'M18',
 'M19',
 'M20',
 'M21',
 'M22',
 'M23',
 'M24',
 'M25',
 'M26',
 'M27',
 'M28',
 'M29',
 'M30',
 'M31',
 'M32',
 'M33',
 'M34',
 'M35',
 'M36',
 'M37',
 'M38',
 'M39',
 'M40',
 'M41',
 'M42',
 'M43',
 'M44',
 'M45',
 'M46',
 'M47',
 'M48',
 'M49',
 'M50',
 'M51',
 'M52',
 'M53',
 'M54',
 'M55',
 'M56',
 'M57',
 'M58',
 'M59',
 'M60',
 'M61',
 'M62',
 'M63',
 'M64',
 'M65',
 'M66',
 'M67',
 'M68',
 'M69',
 'M70',
 'M71',
 'M72',
 'M73',
 'M74',
 'M75',
 'M76',
 'M77',
 'M78',
 'M79',
 'M80',
 'M81',
 'M82',
 'M83',
 'M84',
 'M85',
 'M86',
 'M87',
 'M88',
 'M89',
 'M90']

In [15]:
population_df_filtered = population_df[population_df["LSOA 2021 Name"].str.contains(
    "Devon|Torbay|South Hams|Exeter|Torridge|Teignbridge|Plymouth"
    )]

population_df_filtered.head()

,LAD 2023 Code,LAD 2023 Name,LSOA 2021 Code,LSOA 2021 Name,Total,F0,F1,F2,F3,F4,...,M81,M82,M83,M84,M85,M86,M87,M88,M89,M90
3185,E06000026,Plymouth,E01015023,Plymouth 003A,1750,7,5,2,12,13,...,3,2,1,3,0,0,0,0,0,7
3186,E06000026,Plymouth,E01015024,Plymouth 004A,1264,3,3,6,3,1,...,6,3,4,1,6,2,0,0,1,2
3187,E06000026,Plymouth,E01015025,Plymouth 001A,1712,4,1,3,8,3,...,7,7,5,9,7,4,6,4,5,17
3188,E06000026,Plymouth,E01015026,Plymouth 003B,1493,9,7,8,10,16,...,3,0,1,1,2,1,0,0,1,1
3189,E06000026,Plymouth,E01015027,Plymouth 002A,1669,5,5,3,5,5,...,1,7,4,7,1,1,2,1,1,3

In [48]:
population_df_filtered["F50-84"] = population_df_filtered[
    [f"F{i}" for i in range(50, 84)]
].sum(axis=1)

population_df_filtered["M50-84"] = population_df_filtered[
    [f"M{i}" for i in range(50, 84)]
].sum(axis=1)

# population_df_filtered["F18-49"] = population_df_filtered[
#     [f"F{i}" for i in range(18, 49)]
# ].sum(axis=1)

# population_df_filtered["M18-49"] = population_df_filtered[
#     [f"M{i}" for i in range(18, 49)]
# ].sum(axis=1)

# population_df_filtered["F71+"] = population_df_filtered[
#     [f"F{i}" for i in range(71, 90)]
# ].sum(axis=1)

# population_df_filtered["M71+"] = population_df_filtered[
#     [f"M{i}" for i in range(71, 90)]
# ].sum(axis=1)

C:\Users\Sammi\AppData\Local\Temp\ipykernel_60188\3595762544.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  population_df_filtered["F50-84"] = population_df_filtered[
C:\Users\Sammi\AppData\Local\Temp\ipykernel_60188\3595762544.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  population_df_filtered["M50-84"] = population_df_filtered[

In [52]:
# demand_df = population_df_filtered[["LSOA 2021 Code", "LSOA 2021 Name", "Total", "F18-49", "M18-49", "F50-70", "M50-70", "F71+", "M71+"]].copy()

demand_df = population_df_filtered[["LSOA 2021 Code", "LSOA 2021 Name", "Total", "F50-84", "M50-84"]].copy()
demand_df["MF50-84"] = demand_df["F50-84"] + demand_df["M50-84"]

In [53]:
demand_df

      LSOA 2021 Code   LSOA 2021 Name  Total  F50-84  M50-84  MF50-84
3185       E01015023    Plymouth 003A   1750     321     309      630
3186       E01015024    Plymouth 004A   1264     298     285      583
3187       E01015025    Plymouth 001A   1712     437     413      850
3188       E01015026    Plymouth 003B   1493     253     245      498
3189       E01015027    Plymouth 002A   1669     367     331      698
...              ...              ...    ...     ...     ...      ...
11227      E01020340  West Devon 004D   1890     474     468      942
11228      E01020341  West Devon 006C   1670     509     445      954
11229      E01020342  West Devon 006D   1555     376     345      721
11230      E01034642  West Devon 001E   1609     416     381      797
11231      E01034643  West Devon 001F   2438     329     332      661

[729 rows x 6 columns]

In [44]:
demand_df["F50-70 Percentage of Total LSOA Population"] = demand_df["F50-70"]/ demand_df["Total"]

In [45]:
demand_df.sort_values("F50-70 Percentage of Total LSOA Population")

,LSOA 2021 Code,LSOA 2021 Name,Total,F18-49,M18-49,F50-70,M50-70,F71+,M71+,F50-70 Percentage of Total LSOA Population
3216,E01015054,Plymouth 027B,3170,1486,1391,63,70,20,12,0.019874
3212,E01015050,Plymouth 023D,2041,762,860,68,113,69,47,0.033317
10894,E01020019,Exeter 004B,1903,814,679,68,85,108,49,0.035733
3213,E01015051,Plymouth 023E,1898,731,762,71,83,34,50,0.037408
10917,E01034629,Exeter 001H,3805,1477,1620,144,126,102,116,0.037845
...,...,...,...,...,...,...,...,...,...,...
10982,E01020099,North Devon 002A,1373,145,135,275,254,160,162,0.200291
11009,E01020126,North Devon 002D,1629,212,184,336,309,163,161,0.206262
11202,E01020314,West Devon 004A,1705,208,221,352,278,158,171,0.206452
11205,E01020317,West Devon 006A,1463,158,147,309,238,179,193,0.211210
11038,E01020153,South Hams 004A,1053,89,95,229,203,159,159,0.217474

In [46]:
demand_df.sort_values("F50-70")

,LSOA 2021 Code,LSOA 2021 Name,Total,F18-49,M18-49,F50-70,M50-70,F71+,M71+,F50-70 Percentage of Total LSOA Population
3216,E01015054,Plymouth 027B,3170,1486,1391,63,70,20,12,0.019874
3212,E01015050,Plymouth 023D,2041,762,860,68,113,69,47,0.033317
10894,E01020019,Exeter 004B,1903,814,679,68,85,108,49,0.035733
3215,E01015053,Plymouth 027A,1345,461,561,69,110,7,14,0.051301
3213,E01015051,Plymouth 023E,1898,731,762,71,83,34,50,0.037408
...,...,...,...,...,...,...,...,...,...,...
11027,E01020142,South Hams 006A,2886,457,451,456,379,198,209,0.158004
10835,E01032628,East Devon 004G,2905,465,420,460,383,261,225,0.158348
11060,E01020175,South Hams 011B,2483,289,259,460,390,307,285,0.185260
11045,E01020160,South Hams 002C,3262,652,532,466,423,163,172,0.142857
10828,E01019961,East Devon 007E,2566,278,246,508,483,289,288,0.197973

In [47]:
demand_df.to_csv("demand_F_50_70.csv", index=False)